spring.application.name=SistemaBancario

# DATOS DE CONEXION A MYSQL


spring.datasource.url=jdbc:mysql://localhost:3306/sistema_bancario_bd?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACION JPA / HIBERNATE


#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update

#Con update, Hibernate solo añade lo nuevo que detecte en el codigo, pero respeta las tablas y los registros que ya existen.
spring.jpa.show-sql=true
# Opciones: none | validate | update | create | create-drop
# update  recomendado para desarrollo

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURACIoN OPCIONAL


spring.jpa.open-in-view=false



# configurar patron del log

loggin.level.root=INFO
loggin.patern.console=[%thread] %-5level: %logger - %msg%n


# desactivar banner del spring boot

spring.main.banner-mode=off

